POST http://localhost:3000/posts 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWJyYWFtQGVtYWQuY29tIiwiaWF0IjoxNzUwNjc1ODgzLCJleHAiOjE3NTA2Nzk0ODMsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.aPS67lOt6E6b-p66nVrRPY-k5gnL61a2tp1VfaeR_9Q

{
    "title": "test title 12",
    "postType": "post",
    "slug": "test-slug-13",
    "status": "draft",
    "content": "test content",
    "featuredImageUrl": "https://example.com/image.jpg",
    "publishedOn": "2022-01-01T00:00:00.000Z",
    "tags": ["68627e7c486f6acacaf3054b", "68627e92486f6acacaf3054d"],
    "metaOptions": {
        "metaValue": "{\"sidebarEnabled\": true, \"sidebarPosition\": \"right\"}"
    },
    "author": "68626b15a8aeb7aaa18140ce"
}